name: deploy
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true
      - uses: asdf-vm/actions/install@6278efebb38ae025cc91dd008910f549e775a8c8
      - run: |
          pnpm install
          pnpm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - uses: actions/deploy-pages@v4
